sudo: false

language: "python"

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

install:
    - "pip install ."
    - "pip install -U coveralls flake8"

script:
    - "coverage run --include='cdblib/*.py' setup.py test"
    - "flake8 ."

notifications:
    - email: false

after_success:
    - "coveralls"
